Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2018-04, with the labels that each got.

#296 Python 3 conversion
  .travis.yml
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  fec_integration_tests/interface/interface_functions/test_memory_io.py
  fec_integration_tests/test_buffer_manager_listener_creation.py
  fec_integration_tests/utilities/scp/test_iobuf_clear_process.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/buffer_management/recording_utilities.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_sending_region.py
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/chip_provenance_updater.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/profile_data_gatherer.py
  spinn_front_end_common/interface/interface_functions/tdma_agenda_builder.py
  spinn_front_end_common/interface/profiling/profile_utils.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/interface/simulation/simulation_utilities.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_connection.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_chip_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_report.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/interface/interface_functions/test_front_end_common_graph_binary_gatherer.py
Labels: enhancement

#311 Fix spalloc close
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
Labels: bug

#314 Travis build java
  .travis.yml
  java_common/.gitignore
  java_common/build.xml
Labels: enhancement, minor

#306 Add reset of reloadable regions after DSG
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
Labels: bug
