Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2018-10, with the labels that each got.

#352 Cores can now be in paused or ready state
  spinn_front_end_common/interface/interface_functions/chip_runtime_updater.py
Labels: bug

#353 Python3 cares about the difference between string and bytestring
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_connection.py
Labels: bug

#340 supports spinnaker_2 vm
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#356 Fix command sender machine vertex
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
Labels: bug, enhancement

#357 Fix finisher
  spinn_front_end_common/interface/interface_functions/application_finisher.py
  unittests/interface/interface_functions/test_front_end_common_app_finisher.py
Labels: bug

#360 Allow FEC_DEBUG to be set by higher-level makefile
  c_common/front_end_common_lib/local.mk
Labels: bug

#362 Allow applications to specify use of PROFILER from their own Makefile
  c_common/front_end_common_lib/local.mk
Labels: bug, enhancement

#366 W605
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
Labels: bug

#367 Add missing argument in iobuf extractor
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug
