Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-11, with the labels that each got.

#511 Deal with empty send_buffer_times properly when installing
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: bug

#509 check buffer times at app level as machine level does not pick up too long
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: enhancement

#495 cherry picked app prov folder vs system folder
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/application_runner.py
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/locate_executable_start_type.py
  spinn_front_end_common/mapping_algorithms/front_end_common_mapping_algorithms.xml
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/compression.py
  spinn_front_end_common/utilities/helpful_functions.py
  unittests/interface/interface_functions/test_front_end_common_chip_iobuf_extractor.py
  unittests/interface/interface_functions/test_front_end_common_graph_binary_gatherer.py
  unittests/interface/interface_functions/test_router_compressor.py
Labels: enhancement

#507 Max cores per chip
  fec_integration_tests/file_convertor_tests/test_convert_to_json_machine.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/hbp_max_machine_generator.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/spalloc_max_machine_generator.py
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/helpful_functions.py
  unittests/interface/interface_functions/test_router_compressor.py
  unittests/utilities/test_helpful_functions.py
Labels: enhancement

#513 Multirun provenance
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/graph_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/placements_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
Labels: bug

#516 safety check for prov_items.extend(
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: BLOCKER!, bug

#510 Get machine clean
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: bug

#523 timestep in microsecond
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
Labels: enhancement

#525 run round up to nearest machine_time_step with info and warn if needed
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#527 Don't run iobuf clearer if graph(s) empty
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug
