Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-08, with the labels that each got.

#463 Fix error cores
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: enhancement

#461 Remove unused function within new API, fix spelling
  c_common/front_end_common_lib/include/recording.h
  c_common/front_end_common_lib/src/recording.c
Labels: minor

#462 Function scope
  c_common/front_end_common_lib/Makefile
  c_common/front_end_common_lib/include/buffered_eieio_defs.h
  c_common/front_end_common_lib/include/data_specification.h
  c_common/front_end_common_lib/include/debug.h
  c_common/front_end_common_lib/include/eieio.h
  c_common/front_end_common_lib/include/profiler.h
  c_common/front_end_common_lib/include/recording.h
  c_common/front_end_common_lib/include/simulation.h
  c_common/front_end_common_lib/src/data_specification.c
  c_common/front_end_common_lib/src/profiler.c
  c_common/front_end_common_lib/src/recording.c
  c_common/front_end_common_lib/src/simulation.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
  c_common/models/extra_monitor_support/src/extra_monitor_support.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
Labels: enhancement, minor

#468 states with cores
  unittests/interface/interface_functions/test_front_end_common_app_finisher.py
Labels: bug

#466 cleaning up stuff
  spinn_front_end_common/utilities/constants.py
Labels: enhancement

#467 Don't kill the machine on the first run
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug, help wanted

#469 5.0.1
  requirements.txt
  setup.py
  spinn_front_end_common/_version.py
Labels: enhancement

#477 No router clockspeed
  fec_integration_tests/file_convertor_tests/spinn2.json
  fec_integration_tests/file_convertor_tests/spinn4.json
  fec_integration_tests/file_convertor_tests/spinn4_fiddle.json
  fec_integration_tests/file_convertor_tests/test_convert_to_json_machine.py
Labels: bug

#478 Ensure that report directories are unique
  spinn_front_end_common/interface/config_handler.py
Labels: bug
