Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-02, with the labels that each got.

#390 Fix for calculation of number of timesteps
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: BLOCKER!, bug

#392 Enable testing with Python 3.7
  .travis.yml
Labels: BLOCKER!, bug

#324 Use a documented and supported thread pool class
  requirements.txt
  setup.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
Labels: bug, minor

#335 Fix 2 issues with memory calculations.
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#373 Cryptic structures? NO THANKS!
  c_common/front_end_common_lib/src/recording.c
Labels: enhancement, minor

#378 fix command sender
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
Labels: bug
