Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-06, with the labels that each got.

#435 Wrapped machine
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  spinn_front_end_common/interface/interface_functions/edge_to_n_keys_mapper.py
  spinn_front_end_common/interface/interface_functions/hbp_max_machine_generator.py
  spinn_front_end_common/interface/interface_functions/spalloc_max_machine_generator.py
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/utilities/report_functions/board_chip_report.py
  unittests/interface/ds/test_ds_data_specification_targets.py
  unittests/interface/ds/test_ds_write_info.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
  unittests/interface/interface_functions/test_router_compressor.py
Labels: enhancement

#347 adds citation and manifest files
  CITATION.cff
  MANIFEST.in
  pypi_to_import
  requirements.txt
  setup.py
  spinn_front_end_common/_version.py
Labels: enhancement

#439 Wrapped2
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/report_functions/energy_report.py
Labels: enhancement

#440 Python 3: Revenge of the divide monster
  spinn_front_end_common/interface/interface_functions/profile_data_gatherer.py
  spinn_front_end_common/interface/profiling/profile_data.py
Labels: bug

#442 Sanity for router timeouts!
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
Labels: bug

#444 Add config option to allow users to disable the fast data in protocol
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: BLOCKER!, bug

#445 Extra monitor message handling
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
  c_common/models/extra_monitor_support/src/extra_monitor_support.c
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
Labels: BLOCKER!, bug

#446 Fix the big_connection test in sPyNNaker8
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
  spinn_front_end_common/utilities/helpful_functions.py
Labels: BLOCKER!, bug

#447 Fix memory IO
  spinn_front_end_common/interface/interface_functions/write_memory_io_data.py
Labels: BLOCKER!, bug
