Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-05, with the labels that each got.

#418 No more on-machine DSE
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/__init__.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_execute_data_specification.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/report_functions/__init__.py
  spinn_front_end_common/utilities/report_functions/front_end_common_reports.xml
  spinn_front_end_common/utilities/report_functions/memory_map_on_chip_report.py
Labels: BLOCKER!, bug

#420 routing summary report
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#421 added _ne__ for the dinasours still using python 2.7
  spinn_front_end_common/interface/ds/data_row_reader.py
Labels: bug

#423 eq funtion needs a param
  spinn_front_end_common/interface/ds/data_row_reader.py
Labels: bug

#385 Use sdp directly for live input
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/database/db.sql
  spinn_front_end_common/utility_models/live_packet_gather.py
Labels: enhancement

#389 better prov reporting
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
Labels: enhancement

#394 SQLite doesn't really have INT
  spinn_front_end_common/utilities/database/db.sql
Labels: minor

#434 Actually make sure an individual word gets sent during speed up protocol
  c_common/models/extra_monitor_support/src/extra_monitor_support.c
Labels: bug

#397 NUKED write_reload_steps config value!
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: minor
