Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-07, with the labels that each got.

#408 Sane DSR API types
  c_common/front_end_common_lib/include/data_specification.h
  c_common/front_end_common_lib/src/data_specification.c
  c_common/front_end_common_lib/src/recording.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
Labels: enhancement, minor

#451 Fix sizes of messages written and add a timeout to the gatherer
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
Labels: BLOCKER!, bug

#417 JsonMachine
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#449 ignore bad ethernets
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#453 Remove superfluous check
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: bug

#430 Compression
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#448 Small spelling corrections and other miscellanea
  c_common/models/extra_monitor_support/src/extra_monitor_support.c
  spinn_front_end_common/abstract_models/abstract_changable_after_run.py
  spinn_front_end_common/abstract_models/abstract_generates_data_specification.py
  spinn_front_end_common/abstract_models/abstract_has_associated_binary.py
  spinn_front_end_common/abstract_models/abstract_provides_incoming_partition_constraints.py
  spinn_front_end_common/abstract_models/abstract_provides_n_keys_for_partition.py
  spinn_front_end_common/abstract_models/abstract_provides_outgoing_partition_constraints.py
  spinn_front_end_common/abstract_models/impl/machine_data_specable_vertex.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/preallocate_resources_for_extra_monitor_support.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/tags_loader.py
  spinn_front_end_common/interface/profiling/profile_utils.py
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/mundy_on_chip_router_compression.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
Labels: enhancement, minor

#355 Citation
  CITATION.cff
Labels: enhancement

#450 Better reset support
  c_common/front_end_common_lib/include/simulation.h
  c_common/front_end_common_lib/src/simulation.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
  spinn_front_end_common/abstract_models/__init__.py
  spinn_front_end_common/abstract_models/abstract_can_reset.py
  spinn_front_end_common/abstract_models/abstract_changable_after_run.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/ds/data_specification_targets.py
  spinn_front_end_common/interface/ds/ds_abstact_database.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/interface_functions/buffer_extractor.py
  spinn_front_end_common/interface/interface_functions/chip_runtime_updater.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/utilities/scp/scp_update_runtime_request.py
  spinn_front_end_common/utilities/scp/update_runtime_process.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: bug, enhancement

#438 Part rig
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/edge_to_n_keys_mapper.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
Labels: enhancement

#284 only write database on first run and remapping
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: enhancement

#464 Delete files on region reload
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
Labels: enhancement
