Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-04, with the labels that each got.

#411 Fix router compressor on error
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/mundy_on_chip_router_compression.py
  unittests/interface/interface_functions/test_router_compressor.py
Labels: bug

#412 Two minor changes in the extra monitor core
  c_common/models/extra_monitor_support/src/extra_monitor_support.c
Labels: enhancement, minor

#410 Jenkins2
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/globals_variables.py
Labels: enhancement
