Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-09, with the labels that each got.

#474 N boards
  fec_integration_tests/file_convertor_tests/test_convert_to_json_machine.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/hbp_allocator.py
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
Labels: enhancement

#473 removed paths to nowhere
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: enhancement

#480 Database fixes
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_connection.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/database/db.sql
Labels: bug, enhancement

#470 Manage unigue labels in abstractSpynnaker base only
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_connection.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/database/db.sql
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/simulator_interface.py
Labels: enhancement

#481 recreated deeply hidden class
  spinn_front_end_common/interface/interface_functions/data_in_multicast_routing_generator.py
Labels: BLOCKER!, bug

#479 method to log a float as a hex
  c_common/README.md
  c_common/front_end_common_lib/include/debug.h
  c_common/front_end_common_lib/src/recording.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
Labels: enhancement

#488 added stdlib.h needed by unint32_t
  c_common/front_end_common_lib/include/debug.h
Labels: bug

#487 added stdlib.h needed by unint32_t
  c_common/front_end_common_lib/include/debug.h
Labels: bug

#471 Delete unused
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/ds/data_row_reader.py
  spinn_front_end_common/interface/ds/data_row_writer.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: enhancement
