Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-03, with the labels that each got.

#400 Upgrade to Xenial (gcc 4.9, etc) and colorize the output of gcc
  .travis.yml
Labels: minor

#401 More warnings
  c_common/front_end_common_lib/local.mk
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/data_speed_up_packet_gatherer/src/data_speed_up_packet_gatherer.c
  c_common/models/extra_monitor_support/src/extra_monitor_support.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
Labels: enhancement, minor

#402 Config handler
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/utilities/helpful_functions.py
  unittests/test_spinnaker_main_interface.py
Labels: bug, enhancement

#399 safety time for power off
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#405 Lets not turn off power twice!
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#406 oops! fixed config call
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#393 Deprecation Warnings
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_load_executable_images.py
  fec_integration_tests/mock_machine.py
  setup.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffers_sent_deque.py
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: enhancement
