Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2019-10, with the labels that each got.

#498 Pylint
  .pylintrc
  .travis.yml
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  spinn_front_end_common/abstract_models/impl/machine_allocation_controller.py
  spinn_front_end_common/abstract_models/impl/machine_data_specable_vertex.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_models/sends_buffers_from_host_pre_buffered_impl.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/ds/data_specification_targets.py
  spinn_front_end_common/interface/ds/ds_write_info.py
  spinn_front_end_common/interface/interface_functions/application_runner.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/interface/interface_functions/profile_data_gatherer.py
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/profiling/profile_data.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/constants.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
  spinn_front_end_common/utilities/scp/clear_iobuf_process.py
  spinn_front_end_common/utilities/scp/update_runtime_process.py
  spinn_front_end_common/utilities/simulator_interface.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_messages/speedup_in_scp_commands.py
  spinn_front_end_common/utilities/utility_objs/live_packet_gather_parameters.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/interface/buffer_management/test_buffered_receiver_with_db.py
  unittests/interface/profile/test_profile_data.py
Labels: enhancement, minor

#472 Avoid duplicate info
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  unittests/test_spinnaker_main_interface.py
Labels: enhancement

#484 Data in router without any FAKES!
  spinn_front_end_common/interface/interface_functions/data_in_multicast_routing_generator.py
Labels: enhancement, minor

#502 fixed incorrect import from collections.abc
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_load_executable_images.py
  fec_integration_tests/mock_machine.py
  setup.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffers_sent_deque.py
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: bug

#496 Allow for larger recordings
  spinn_front_end_common/interface/buffer_management/storage_objects/db.sql
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
Labels: bug

#485 Fix Poisson Sender
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/utility_objs/live_packet_gather_parameters.py
  spinn_front_end_common/utility_models/live_packet_gather.py
Labels: enhancement

#501 Prefix monster
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#486 Constant byte size multipliers
  fec_integration_tests/interface/interface_functions/test_memory_io.py
  spinn_front_end_common/interface/buffer_management/recording_utilities.py
  spinn_front_end_common/interface/buffer_management/storage_objects/channel_buffer_state.py
  spinn_front_end_common/interface/buffer_management/storage_objects/end_buffering_state.py
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/interface_functions/write_memory_io_data.py
  spinn_front_end_common/interface/profiling/profile_utils.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/constants.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
Labels: enhancement, minor

#493 Project eighteen
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/hbp_max_machine_generator.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/spalloc_max_machine_generator.py
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: BLOCKER!, bug

#504 Deal with compiler warnings in minimise functions
  c_common/models/minimise/src/minimise.h
  c_common/models/minimise/src/platform.h
  c_common/models/minimise/src/simple_minimise.c
Labels: bug, help wanted
