Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-06, with the labels that each got.

#608 Routing compression checker from a report to an Algorithm
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: BLOCKER!

#584 Doxygen
  .ratexcludes
  .travis.yml
  c_common/.gitignore
  c_common/Doxyfile
  c_common/front_end_common_lib/include/buffered_eieio_defs.h
  c_common/front_end_common_lib/include/common-typedefs.h
  c_common/front_end_common_lib/include/data_specification.h
  c_common/front_end_common_lib/include/debug.h
  c_common/front_end_common_lib/include/eieio.h
  c_common/front_end_common_lib/include/filter_info.h
  c_common/front_end_common_lib/include/key_atom_map.h
  c_common/front_end_common_lib/include/malloc_extras.h
  c_common/front_end_common_lib/include/profiler.h
  c_common/front_end_common_lib/include/recording.h
  c_common/front_end_common_lib/include/sdp_no_scp.h
  c_common/front_end_common_lib/include/simulation.h
  c_common/front_end_common_lib/src/data_specification.c
  c_common/front_end_common_lib/src/malloc_extras.c
  c_common/front_end_common_lib/src/profiler.c
  c_common/front_end_common_lib/src/recording.c
  c_common/front_end_common_lib/src/simulation.c
  c_common/mainpage.dox
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/compressor_bit_field_models/src/bit_field_compressor.c
  c_common/models/compressor_bit_field_models/src/bit_field_sorter_and_searcher.c
  c_common/models/compressor_bit_field_models/src/common/bit_field_table_generator.h
  c_common/models/compressor_bit_field_models/src/common/compressor_sorter_structs.h
  c_common/models/compressor_bit_field_models/src/common/constants.h
  c_common/models/compressor_bit_field_models/src/common/routing_table.h
  c_common/models/compressor_bit_field_models/src/common/routing_table_utils.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/aliases.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/bit_set.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/key_mask.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/m_trie.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/merge.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/ordered_covering.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/remove_default_routes.h
  c_common/models/compressor_bit_field_models/src/sorter_includes/bit_field_reader.h
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/minimise/src/minimise.h
  c_common/models/minimise/src/platform.h
  c_common/models/minimise/src/routing_table.h
  c_common/models/minimise/src/simple_minimise.c
  c_common/models/minimise/src/unordered_remove_default_routes.h
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
  c_common/models/system_models/src/common.h
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  c_common/models/system_models/src/extra_monitor_support.c
  doc/global/.nojekyll
  doc/global/index.html
  doc/global/spinnaker.css
Labels: enhancement, minor

#341 Allows vm reporting of cores and links
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
Labels: enhancement

#607 Upgrade Travis Ubuntu distribution to bionic (18.04)
  .travis.yml
Labels: enhancement

#612 reinjector bug
  c_common/models/system_models/src/extra_monitor_support.c
Labels: BLOCKER!, bug

#614 avoid logging an unset variable
  c_common/models/compressor_bit_field_models/src/bit_field_sorter_and_searcher.c
Labels: bug

#615 Bitfeild various fixes
  c_common/front_end_common_lib/src/malloc_extras.c
  c_common/models/compressor_bit_field_models/src/bit_field_compressor.c
  c_common/models/compressor_bit_field_models/src/compressor_includes/ordered_covering.h
  c_common/models/compressor_bit_field_models/src/sorter_includes/bit_field_reader.h
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
Labels: BLOCKER!, bug

#611 import issues
  c_common/models/minimise/src/minimise.h
  c_common/models/minimise/src/platform.h
  c_common/models/minimise/src/simple_minimise.c
Labels: BLOCKER!, bug, enhancement

#619 Pair compressor now send result to user 1 so best to read from there.
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/compression.py
Labels: BLOCKER!, bug

#621 based sdram cost on slice size not all atoms
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: bug

#620 Allow compress_only_when_needed to be turned off
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
Labels: bug
