Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-03, with the labels that each got.

#554 Donal fec changes
  fec_integration_tests/interface/interface_functions/test_front_end_common_load_executable_images.py
  spinn_front_end_common/interface/buffer_management/buffer_models/abstract_sends_buffers_from_host.py
  spinn_front_end_common/interface/buffer_management/buffer_models/sends_buffers_from_host_pre_buffered_impl.py
  spinn_front_end_common/interface/buffer_management/storage_objects/channel_buffer_state.py
  spinn_front_end_common/interface/interface_functions/graph_binary_gatherer.py
  spinn_front_end_common/interface/interface_functions/hbp_max_machine_generator.py
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/compression.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/notification_protocol/__init__.py
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
  spinn_front_end_common/utilities/notification_protocol/socket_address.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_report.py
  spinn_front_end_common/utilities/scp/__init__.py
  spinn_front_end_common/utilities/scp/clear_iobuf_process.py
  spinn_front_end_common/utilities/scp/scp_clear_iobuf_request.py
  spinn_front_end_common/utilities/scp/scp_update_runtime_request.py
  spinn_front_end_common/utilities/scp/update_runtime_process.py
  spinn_front_end_common/utilities/utility_objs/executable_targets.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_messages/get_reinjection_status_message.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_processes/read_status_process.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
Labels: enhancement

#561 Use bulk inserts for faster DB generation
  spinn_front_end_common/interface/interface_functions/provenance_sql_writer.py
  spinn_front_end_common/interface/provenance/db.sql
  spinn_front_end_common/interface/provenance/sqllite_database.py
Labels: bug

#558 Make less verbose in normal operation (yes some packets go missing)
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  spinn_front_end_common/interface/interface_functions/placements_provenance_gatherer.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_processes/read_status_process.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
Labels: enhancement

#557 move all uses of the application_generated_data_files to reports
  fec_integration_tests/interface/interface_functions/test_memory_io.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/write_memory_io_data.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/interface/spinnaker.cfg.template
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
Labels: enhancement

#568 End without run bug
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: enhancement

#571 Quell some warnings picked up by pylint
  spinn_front_end_common/interface/interface_functions/placements_provenance_gatherer.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_processes/read_status_process.py
Labels: bug, minor

#563 Dont require params and then insist they are None!
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
Labels: bug

#575 Exclude a broken release of httpretty
  requirements-test.txt
Labels: BLOCKER!, bug, minor

#574 Pass LPG Params through all the way to the relevant vertices
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/utilities/utility_objs/live_packet_gather_parameters.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
Labels: enhancement, minor

#576 LPG Early Sanity Checking
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/utilities/utility_objs/live_packet_gather_parameters.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
Labels: enhancement, minor

#577 interupt to avoid log clashes
  c_common/front_end_common_lib/include/debug.h
Labels: enhancement

#573 Move logic into query
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/provenance/sqllite_database.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/utility_objs/data_written.py
Labels: enhancement, minor

#579 Cheaper disable/enable of interrupts in logging
  c_common/front_end_common_lib/include/debug.h
Labels: BLOCKER!, bug
