Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-01, with the labels that each got.

#535 Coverage4
  .travis.yml
  requirements-test.txt
Labels: BLOCKER!

#537 Clean up a few bits
  c_common/models/system_models/src/common.h
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  c_common/models/system_models/src/extra_monitor_support.c
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/system_multicast_routing_generator.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: minor

#539 It's pronounced time_scale_factor, not timescale_factor
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: enhancement, minor

#540 Fix unaligned recording
  c_common/front_end_common_lib/include/recording.h
  c_common/front_end_common_lib/src/recording.c
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
Labels: bug
