Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-09, with the labels that each got.

#644 Determinism agdr
  c_common/front_end_common_lib/include/tdma_processing.h
  c_common/front_end_common_lib/src/tdma_processing.c
  spinn_front_end_common/abstract_models/abstract_requires_tdma.py
  spinn_front_end_common/abstract_models/impl/requires_tdma.py
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
Labels: enhancement

#656 UNUSED declarations!
  c_common/Doxyfile
  c_common/front_end_common_lib/src/recording.c
  c_common/front_end_common_lib/src/simulation.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/compressors/src/bit_field_compressor.c
  c_common/models/compressors/src/ordered_covering_includes/bit_set.h
  c_common/models/compressors/src/simple/simple_compressor.c
  c_common/models/compressors/src/sorter/bit_field_sorter_and_searcher.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
Labels: enhancement, minor

#642 compressor cleanup
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/rt_minimise.dict
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/system_control_logic.py
  unittests/interface/interface_functions/test_router_compressor.py
Labels: bug, enhancement

#583 Real bitfields in C
  c_common/Doxyfile
  c_common/front_end_common_lib/Makefile
  c_common/front_end_common_lib/include/spinn_extra.h
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/system_models/src/extra_monitor_support.c
Labels: enhancement

#632 Determism
  c_common/front_end_common_lib/Makefile
  c_common/front_end_common_lib/include/malloc_extras.h
  c_common/front_end_common_lib/include/tdma_processing.h
  c_common/front_end_common_lib/src/malloc_extras.c
  c_common/front_end_common_lib/src/tdma_processing.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
  spinn_front_end_common/abstract_models/impl/__init__.py
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/__init__.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: enhancement

#663 Get rid of signed/unsigned warnings
  c_common/models/compressors/src/bit_field_common/bit_field_table_generator.h
  c_common/models/compressors/src/compressor_includes/pair_minimize.h
  c_common/models/compressors/src/sorter/bit_field_reader.h
Labels: enhancement, minor

#624 Emergency to wait2
  c_common/models/system_models/src/extra_monitor_support.c
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_messages/__init__.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_messages/reinjector_scp_commands.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_messages/set_router_emergency_timeout_message.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_messages/set_router_timeout_message.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_processes/__init__.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_processes/set_router_emergency_timeout_process.py
  spinn_front_end_common/utilities/utility_objs/extra_monitor_scp_processes/set_router_timeout_process.py
  spinn_front_end_common/utilities/utility_objs/reinjection_status.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
Labels: enhancement, minor
