Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-12, with the labels that each got.

#494 cherry picked partitioner
  fec_integration_tests/interface/interface_functions/simple_test_vertex.py
  fec_integration_tests/test_buffer_manager_listener_creation.py
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_extra_monitor_functionality.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py
  spinn_front_end_common/interface/splitter_selectors/__init__.py
  spinn_front_end_common/interface/splitter_selectors/splitter_selector.py
  spinn_front_end_common/utility_models/abstract_one_app_one_machine_vertex.py
  spinn_front_end_common/utility_models/chip_power_monitor.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer.py
  spinn_front_end_common/utility_models/extra_monitor_support.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: enhancement

#718 Enforce machine vertex
  spinn_front_end_common/abstract_models/abstract_can_reset.py
  spinn_front_end_common/abstract_models/abstract_has_associated_binary.py
  spinn_front_end_common/abstract_models/abstract_supports_bit_field_generation.py
  spinn_front_end_common/abstract_models/abstract_supports_bit_field_routing_compression.py
  spinn_front_end_common/abstract_models/abstract_supports_database_injection.py
  spinn_front_end_common/abstract_models/abstract_vertex_with_dependent_vertices.py
  spinn_front_end_common/interface/buffer_management/buffer_models/abstract_receive_buffers_to_host.py
  spinn_front_end_common/interface/buffer_management/buffer_models/abstract_sends_buffers_from_host.py
  spinn_front_end_common/interface/profiling/abstract_has_profile_data.py
  spinn_front_end_common/interface/provenance/abstract_provides_local_provenance_data.py
  spinn_front_end_common/interface/provenance/abstract_provides_provenance_data_from_machine.py
Labels: enhancement

#719 Version binding for numpy
  doc/source/conf.py
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#720 Get rid of stupid aliasing tricks and poking into the guts of PACMAN
  spinn_front_end_common/interface/interface_functions/pre_allocate_resources_for_live_packet_gatherers.py
Labels: bug, minor

#723 Corrections to numpy version requirements
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#706 Fix continue
  c_common/front_end_common_lib/src/simulation.c
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/application_finisher.py
  unittests/interface/interface_functions/test_front_end_common_app_finisher.py
Labels: bug

#724 Bind the version of scipy
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#728 Dont die if there is no vertex which needs clearing
  spinn_front_end_common/interface/interface_functions/chip_iobuf_clearer.py
Labels: bug

#714 removed unused io functionality
  fec_integration_tests/interface/interface_functions/test_memory_io.py
  spinn_front_end_common/abstract_models/__init__.py
  spinn_front_end_common/abstract_models/abstract_uses_memory_io.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/write_memory_io_data.py
Labels: enhancement

#711 Convert workflows to use common actions
  .github/workflows/c_actions.yml
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
Labels: enhancement, minor

#731 Cut over the last bits of the travis build
  .github/workflows/c_actions.yml
  .github/workflows/python_actions.yml
  .travis.yml
Labels: enhancement, minor
