Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-10, with the labels that each got.

#669 fixy fixy for donal
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
Labels: BLOCKER!, bug, enhancement, minor

#668 No more storage handlers
  .travis.yml
  README.md
  doc/doc_requirements.txt
  doc/source/conf.py
  pypi_to_import
  requirements.txt
  setup.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/ds/__init__.py
  spinn_front_end_common/interface/ds/data_row_reader.py
  spinn_front_end_common/interface/ds/data_row_writer.py
  spinn_front_end_common/interface/ds/data_specification_targets.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  unittests/interface/ds/test_ds_data_specification_targets.py
  unittests/test_version.py
Labels: bug, enhancement, minor

#672 fix for command sender
  spinn_front_end_common/utility_models/abstract_one_app_one_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
Labels: bug, enhancement

#670 Even Alan can not measure power on virtual chips
  spinn_front_end_common/interface/interface_functions/insert_chip_power_monitors_to_graphs.py
Labels: bug

#671 Pop based master pop table
  c_common/front_end_common_lib/include/filter_info.h
  c_common/front_end_common_lib/include/key_atom_map.h
  c_common/models/compressors/src/bit_field_common/compressor_sorter_structs.h
  c_common/models/compressors/src/bit_field_common/routing_tables.h
  c_common/models/compressors/src/sorter/bit_field_reader.h
  c_common/models/compressors/src/sorter/bit_field_sorter_and_searcher.c
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/utilities/system_control_logic.py
Labels: enhancement

#678 remembering machine_vertex called by machine_graph
  spinn_front_end_common/interface/interface_functions/insert_extra_monitor_vertices_to_graphs.py
  spinn_front_end_common/utility_models/abstract_one_app_one_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer.py
  spinn_front_end_common/utility_models/extra_monitor_support.py
Labels: enhancement

#680 Use the AbstractContextManager from SpiNNUtils
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/provenance/sqllite_database.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
Labels: enhancement, minor

#683 One to one splitter
  spinn_front_end_common/interface/splitter_selectors/splitter_selector.py
  spinn_front_end_common/utility_models/abstract_one_app_one_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer.py
  spinn_front_end_common/utility_models/extra_monitor_support.py
Labels: enhancement

#687 Add a couple of missing functions
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/simulator_interface.py
Labels: bug
