Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-05, with the labels that each got.

#582 Actually call ChipIOBufClearer when in multirun mode
  .travis.yml
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug, minor

#595 Don't clear out the iobuf during initialisation steps
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
Labels: bug

#596 All algorithms comms sdram
  .travis.yml
  c_common/models/Makefile
  c_common/models/compressor_bit_field_models/src/bit_field_compressor.c
  c_common/models/compressor_bit_field_models/src/bit_field_sorter_and_searcher.c
  c_common/models/compressor_bit_field_models/src/common/compressor_sorter_structs.h
  c_common/models/compressor_bit_field_models/src/compressor_includes/ordered_covering.h
  c_common/models/compressor_bit_field_models/src/sorter_includes/bit_field_reader.h
  c_common/models/compressor_bit_field_models/src/sorter_includes/bit_field_table_generator.h
  c_common/models/compressor_bit_field_models/src/sorter_includes/helpful_functions.h
  c_common/models/compressor_bit_field_models/src/sorter_includes/message_sending.h
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/graph_binary_gatherer.py
  spinn_front_end_common/interface/interface_functions/load_executable_images.py
  spinn_front_end_common/interface/interface_functions/locate_executable_start_type.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/compression.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/system_control_logic.py
  spinn_front_end_common/utilities/utility_objs/__init__.py
  spinn_front_end_common/utilities/utility_objs/executable_targets.py
  unittests/interface/interface_functions/test_front_end_common_chip_iobuf_extractor.py
  unittests/interface/interface_functions/test_front_end_common_graph_binary_gatherer.py
Labels: bug, enhancement

#597 Report overruns correctly
  .travis.yml
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
Labels: bug, enhancement

#600 prov reader
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#598 Make IOBuf clearer work with run_until_complete
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#604 Prevent a buffer overrun in the LPG when using packets with payloads
  c_common/models/live_packet_gather/src/live_packet_gather.c
Labels: BLOCKER!, bug
