Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-08, with the labels that each got.

#643 Generate a fec.tag file in the docs and cross link to dependencies
  .ratexcludes
  .travis.yml
  c_common/.common_template.tag
  c_common/.gitignore
  c_common/.sllt_template.tag
  c_common/Doxyfile
  c_common/Makefile
Labels: enhancement

#645 Add testing with Python 3.8
  .travis.yml
  setup.py
  spinn_front_end_common/interface/ds/data_specification_targets.py
Labels: enhancement, minor

#648 Moved get_n_keys_for_partition to MachineVertex
  spinn_front_end_common/abstract_models/__init__.py
  spinn_front_end_common/abstract_models/abstract_provides_n_keys_for_partition.py
  spinn_front_end_common/interface/interface_functions/edge_to_n_keys_mapper.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py
Labels: enhancement

#649 Binary from machine
  spinn_front_end_common/interface/interface_functions/graph_binary_gatherer.py
  spinn_front_end_common/interface/interface_functions/locate_executable_start_type.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utility_models/chip_power_monitor.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: enhancement

#653 fixes the compressors in a multiude of ways.
  c_common/models/compressors/src/bit_field_common/bit_field_table_generator.h
  c_common/models/compressors/src/bit_field_common/routing_tables.h
  c_common/models/compressors/src/common/routing_table.h
  c_common/models/compressors/src/compressor_includes/pair_minimize.h
  c_common/models/compressors/src/sorter/bit_field_sorter_and_searcher.c
Labels: BLOCKER!, bug

#654 AbstractSupportsBitFieldRoutingCompression on Machine Vertexes only!
  spinn_front_end_common/abstract_models/abstract_supports_bit_field_routing_compression.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
Labels: enhancement
