Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-11, with the labels that each got.

#688 stop making an unused binary
  c_common/models/compressors/Makefile
  c_common/models/compressors/compressor.mk
Labels: bug

#685 Minor changes to the OneAppOneMachine Vertex
  spinn_front_end_common/utility_models/abstract_one_app_one_machine_vertex.py
Labels: enhancement

#686 check machine level first
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/process_partition_constraints.py
Labels: enhancement

#690 Fixes for the Python docs
  doc/source/conf.py
  spinn_front_end_common/abstract_models/abstract_provides_key_to_atom_mapping.py
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/buffer_management/storage_objects/abstract_database.py
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/interface_functions/application_runner.py
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/load_executable_images.py
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/__init__.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
  spinn_front_end_common/interface/interface_functions/pre_allocate_resources_for_live_packet_gatherers.py
  spinn_front_end_common/interface/provenance/sqllite_database.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/simulator_interface.py
  spinn_front_end_common/utilities/system_control_logic.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  unittests/interface/interface_functions/test_router_compressor.py
Labels: bug, minor

#692 python actions.
  .github/workflows/python_actions.yml
  .ratexcludes
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
Labels: BLOCKER!, enhancement

#696 python actions with Sphinx turned on
  .github/workflows/python_actions.yml
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
Labels: enhancement

#693 Add C actions
  .github/workflows/c_actions.yml
Labels: BLOCKER!, enhancement

#699 A workflow for doing publishing
  .github/workflows/publish.yml
Labels: BLOCKER!, enhancement

#694 sersiously. that was easy
  spinn_front_end_common/utility_models/chip_power_monitor.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: enhancement

#691 adjust api accordingly.
  spinn_front_end_common/abstract_models/abstract_rewrites_data_specification.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
Labels: enhancement

#679 allows key constriants on vertex to be applied to all outgoing constr…
  spinn_front_end_common/interface/interface_functions/process_partition_constraints.py
Labels: bug, enhancement

#702 Fix -Wshadow compiler warnings
  c_common/models/compressors/src/sorter/bit_field_sorter_and_searcher.c
Labels: bug

#689 Application Vertices should make sure n_atoms is an int
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: enhancement

#666 Run synchronized
  c_common/front_end_common_lib/include/simulation.h
  c_common/front_end_common_lib/src/simulation.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/chip_runtime_updater.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/scp/update_runtime_process.py
  spinn_front_end_common/utilities/simulator_interface.py
Labels: enhancement

#712 DSGRegionReloader little cleanup
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
Labels: minor

#710 InsertEdgesToExtraMonitorFunctionality cleanup
  spinn_front_end_common/interface/interface_functions/insert_edges_to_extra_monitor_functionality.py
Labels: minor

#707 clone partitions when building new machine graphs
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: BLOCKER!, bug
