Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-02, with the labels that each got.

#517 issue closed test does not need to be skipped
  unittests/interface/interface_functions/test_front_end_common_app_finisher.py
Labels: enhancement

#545 json files should end with .json
  spinn_front_end_common/interface/interface_functions/provenance_json_writer.py
Labels: bug

#549 Detect router errors
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
Labels: enhancement

#548 Fix compressor error
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/compression.py
Labels: bug

#518 Fix injection
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: bug

#547 fewer timeouts
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: enhancement

#550 Tidy up debug print left in by mistake
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: minor

#546 Provenance sql
  .ratexcludes
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/__init__.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/provenance_sql_writer.py
  spinn_front_end_common/interface/provenance/db.sql
  spinn_front_end_common/interface/provenance/sqllite_database.py
  spinn_front_end_common/interface/spinnaker.cfg
  unittests/interface/interface_functions/test_output/.gitignore
  unittests/interface/interface_functions/test_provenace_writers.py
Labels: enhancement

#532 Fix router table copy
  c_common/models/system_models/src/extra_monitor_support.c
Labels: bug

#543 Json files
  fec_integration_tests/file_convertor_tests/.gitignore
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#555 Revert "Fix router table copy"
  c_common/models/system_models/src/extra_monitor_support.c
Labels: bug
