Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2020-07, with the labels that each got.

#565 Count router errors
  c_common/models/system_models/src/extra_monitor_support.c
Labels: bug, enhancement

#602 Proper reboot wait
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#625 Deal with case where a vertex_slice has an array of empty arrays
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: bug

#454 Simple reporting of actual tags on machine
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/utilities/report_functions/__init__.py
  spinn_front_end_common/utilities/report_functions/front_end_common_reports.xml
  spinn_front_end_common/utilities/report_functions/real_tags_report.py
Labels: enhancement, help wanted

#633 router diagnositcs misleading
  spinn_front_end_common/interface/interface_functions/application_runner.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
Labels: BLOCKER!, bug

#636 tweeky tweeky
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/compression.py
  spinn_front_end_common/utilities/system_control_logic.py
Labels: enhancement

#638 Implement BufferedReceivingData.clear
  spinn_front_end_common/interface/buffer_management/storage_objects/abstract_database.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
Labels: bug, enhancement, minor

#639 accum all the algorithms into interface functions
  spinn_front_end_common/interface/interface_functions/find_application_chips_used.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/__init__.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/compression.py
  spinn_front_end_common/interface/interface_functions/on_chip_router_table_compression/rt_minimise.aplx
  spinn_front_end_common/mapping_algorithms/front_end_common_mapping_algorithms.xml
  spinn_front_end_common/mapping_algorithms/on_chip_router_table_compression/__init__.py
  spinn_front_end_common/utilities/function_list.py
  unittests/interface/interface_functions/test_router_compressor.py
Labels: enhancement

#641 more views of the prov db to make it easier to use
  spinn_front_end_common/interface/provenance/db.sql
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
Labels: enhancement

#640 removed comment with list of algorithm names as out of date
  spinn_front_end_common/interface/spinnaker.cfg
Labels: bug
