Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-08, with the labels that each got.

#843 Compressors sdram
  c_common/front_end_common_lib/src/malloc_extras.c
  c_common/models/compressors/src/simple/simple_compressor.c
Labels: bug, enhancement

#844 Use the python-tools action in order to fix pip version
  .github/workflows/publish.yml
Labels: bug

#845 Add app ID to database
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/utilities/database/database_writer.py
Labels: enhancement
