Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-02, with the labels that each got.

#742 adds dial to shut up waiting report
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#729 GraphBinaryGatherer check for Binary or Virtual
  spinn_front_end_common/interface/interface_functions/graph_binary_gatherer.py
Labels: enhancement

#716 remove AbstractRecordable as it was never used correctly
  spinn_front_end_common/abstract_models/__init__.py
  spinn_front_end_common/abstract_models/abstract_recordable.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/database/db.sql
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: bug

#661 Router provenance mapper utility
  .images/External_P2P_Packets.png
  README.md
  setup.py
  spinn_front_end_common/interface/provenance/db.sql
  spinn_front_end_common/interface/provenance/router_prov_mapper.py
Labels: enhancement

#713 added a comment that app level only checked if machine not implemented
  spinn_front_end_common/abstract_models/abstract_provides_outgoing_partition_constraints.py
  spinn_front_end_common/utility_models/command_sender.py
Labels: minor

#726 Host bitfield compressor cleanup
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/utilities/constants.py
  spinn_front_end_common/utilities/report_functions/bit_field_compressor_report.py
  unittests/interface/interface_functions/test_host_but_field_router_compressor.py
Labels: bug, enhancement

#745 fix write_bit_field_compressor_report
  spinn_front_end_common/utilities/report_functions/bit_field_compressor_report.py
  spinn_front_end_common/utilities/report_functions/front_end_common_reports.xml
Labels: BLOCKER!, bug

#722 Use new transceiver API for reading a single word
  spinn_front_end_common/interface/buffer_management/recording_utilities.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/profiling/profile_utils.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
  unittests/interface/profile/test_profile_data.py
Labels: enhancement, minor

#749 Bit field sdram calcs
  c_common/front_end_common_lib/src/recording.c
  spinn_front_end_common/interface/buffer_management/recording_utilities.py
  spinn_front_end_common/interface/buffer_management/storage_objects/channel_buffer_state.py
Labels: bug, enhancement

#750 A minor improvement to our .gitignore
  .gitignore
Labels: bug, minor

#751 Prealloc cleanup
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/pre_allocate_for_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/pre_allocate_resources_for_chip_power_monitor.py
  spinn_front_end_common/interface/interface_functions/pre_allocate_resources_for_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/preallocate_resources_for_extra_monitor_support.py
Labels: bug, minor

#752 added 3.9 and rat 3.8
  .github/workflows/c_actions.yml
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
  setup.py
Labels: enhancement, minor

#753 Emergency fix; failed integration testing
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: BLOCKER!, bug

#758 Fix circular import
  spinn_front_end_common/utilities/system_control_logic.py
Labels: BLOCKER!, bug

#760 remove unnneded _py3
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: minor

#730 Remove circular dependency
  doc/source/conf.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/__init__.py
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/find_application_chips_used.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/utilities/__init__.py
  spinn_front_end_common/utilities/emergency_recovery.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/iobuf_extractor.py
  spinn_front_end_common/utilities/report_functions/__init__.py
  spinn_front_end_common/utilities/report_functions/bit_field_compressor_report.py
  spinn_front_end_common/utilities/system_control_logic.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  unittests/interface/test_xml_file_path.py
Labels: bug

#756 Lost spike issues
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/constants.py
Labels: bug, enhancement

#762 More exposed via global variables
  fec_integration_tests/base_test_case.py
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/globals_variables.py
Labels: enhancement

#763 Test base2
  fec_integration_tests/base_test_case.py
Labels: minor
