Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-04, with the labels that each got.

#781 Bump6.0.1
  doc/source/conf.py
  requirements.txt
  setup.py
  spinn_front_end_common/_version.py
Labels: next_release

#783 java_jar_path
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/spinnaker.cfg
  unittests/interface/test_java_caller.py
  unittests/mock/SpiNNaker-front-end/target/spinnaker-exe.jar
  unittests/mock/spinnaker-exe.jar
Labels: enhancement

#787 Tags passed as Tags object only
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/tags_loader.py
Labels: bug

#791 Remove dead inputs
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: minor

#790 Making the configs truly global
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/interface/spinnaker.cfg.template
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/globals_variables.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/simulator_interface.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  unittests/test_spinnaker_main_interface.py
Labels: enhancement

#795 test decode the xml files
  unittests/interface/interface_functions/test_xml.py
Labels: enhancement

#797 find and check all get_config calls
  unittests/test_cfg_checker.py
Labels: enhancement

#798 Router max entries from Machine
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
Labels: enhancement

#799 Fix extra monitor memory leak
  c_common/models/system_models/src/extra_monitor_support.c
Labels: bug
