Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-09, with the labels that each got.

#520 should only report finished when you actually finish successfully.
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: bug, enhancement

#869 fix prov call on error
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#870 Spalloc avoid boards
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement, blocker
