Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-06, with the labels that each got.

#821 Add tolerance of 1 core in Json comparison
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
Labels: blocker

#808 report provenace right away
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/utility_objs/provenance_data_item.py
Labels: enhancement

#820 PacmanAlgorithmFailedToCompleteException never used so why check for it
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#775 Test objects
  fec_integration_tests/interface/interface_functions/simple_test_vertex.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_load_executable_images.py
  fec_integration_tests/test_buffer_manager_listener_creation.py
  unittests/interface/interface_functions/test_front_end_common_app_finisher.py
  unittests/interface/interface_functions/test_front_end_common_chip_iobuf_extractor.py
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
  unittests/interface/interface_functions/test_front_end_common_graph_binary_gatherer.py
  unittests/interface/interface_functions/test_front_end_common_tags_loader.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
Labels: enhancement

#823 remove turn_off_board_after_discovery
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: minor

#822 Graph view
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#824 Too broad an exception is not a good idea
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
Labels: minor

#827 Fix app master pop limits
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
Labels: bug

#828 Unittest setup
  fec_integration_tests/empty_test.py
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_load_executable_images.py
  fec_integration_tests/test_buffer_manager_listener_creation.py
  fec_integration_tests/utilities/notification_protocol/test_start_resume_notification_protocol.py
  fec_integration_tests/utilities/notification_protocol/test_stop_pause_notification_protocol.py
  fec_integration_tests/utilities/scp/test_iobuf_clear_process.py
  spinn_front_end_common/interface/config_setup.py
  spinn_front_end_common/utilities/globals_variables.py
  unittests/interface/buffer_management/test_buffered_receiver_with_db.py
  unittests/interface/ds/test_ds_data_specification_targets.py
  unittests/interface/ds/test_ds_write_info.py
  unittests/interface/interface_functions/test_front_end_common_app_finisher.py
  unittests/interface/interface_functions/test_front_end_common_chip_iobuf_extractor.py
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
  unittests/interface/interface_functions/test_front_end_common_graph_binary_gatherer.py
  unittests/interface/interface_functions/test_front_end_common_spalloc_max_machine_generator.py
  unittests/interface/interface_functions/test_front_end_common_tags_loader.py
  unittests/interface/interface_functions/test_hbp_allocator.py
  unittests/interface/interface_functions/test_host_but_field_router_compressor.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
  unittests/interface/interface_functions/test_provenace_writers.py
  unittests/interface/interface_functions/test_xml.py
  unittests/interface/profile/test_profile_data.py
  unittests/interface/test_java_caller.py
  unittests/interface/test_xml_file_path.py
  unittests/test_cfg_checker.py
  unittests/test_import_all_test.py
  unittests/test_spinnaker_main_interface.py
  unittests/test_version.py
Labels: enhancement

#826 report directories as global_variables
  fec_integration_tests/test_buffer_manager_listener_creation.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/ds/data_specification_targets.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/interface_functions/buffer_manager_creator.py
  spinn_front_end_common/interface/interface_functions/chip_iobuf_extractor.py
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py
  spinn_front_end_common/interface/interface_functions/insert_extra_monitor_vertices_to_graphs.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/profile_data_gatherer.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/emergency_recovery.py
  spinn_front_end_common/utilities/globals_variables.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/iobuf_extractor.py
  spinn_front_end_common/utilities/report_functions/bit_field_compressor_report.py
  spinn_front_end_common/utilities/report_functions/board_chip_report.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
  spinn_front_end_common/utilities/report_functions/fixed_route_from_machine_report.py
  spinn_front_end_common/utilities/report_functions/front_end_common_reports.xml
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_report.py
  spinn_front_end_common/utilities/report_functions/network_specification.py
  spinn_front_end_common/utilities/report_functions/real_tags_report.py
  spinn_front_end_common/utilities/report_functions/reports.py
  spinn_front_end_common/utilities/report_functions/router_collision_potential_report.py
  spinn_front_end_common/utilities/report_functions/routing_compression_report.py
  spinn_front_end_common/utilities/report_functions/routing_table_from_machine_report.py
  spinn_front_end_common/utilities/system_control_logic.py
  spinn_front_end_common/utilities/utility_calls.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  unittests/interface/buffer_management/test_buffered_receiver_with_db.py
  unittests/interface/ds/test_ds_data_specification_targets.py
  unittests/interface/ds/test_ds_write_info.py
  unittests/interface/interface_functions/test_front_end_common_chip_iobuf_extractor.py
  unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
  unittests/utilities/test_utilities.py
Labels: enhancement

#825 Bye bye outer_table_compression_target_length setting
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: minor

#815 Split synapse neuron models
  c_common/front_end_common_lib/include/simulation.h
  c_common/front_end_common_lib/include/tdma_processing.h
  c_common/front_end_common_lib/include/wfi.h
  c_common/front_end_common_lib/src/simulation.c
  c_common/front_end_common_lib/src/tdma_processing.c
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_edges_to_live_packet_gatherers.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_insert_lpgs.py
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/recording_utilities.py
  spinn_front_end_common/interface/interface_functions/chip_provenance_updater.py
  spinn_front_end_common/interface/interface_functions/front_end_common_interface_functions.xml
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
  spinn_front_end_common/interface/interface_functions/sdram_outgoing_partition_allocator.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/database/db.sql
  spinn_front_end_common/utilities/emergency_recovery.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/iobuf_extractor.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
Labels: enhancement
