Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-05, with the labels that each got.

#681 More provenance
  c_common/models/command_sender_multicast_source/src/command_sender_multicast_source.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  c_common/models/system_models/src/extra_monitor_support.c
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/chip_provenance_updater.py
  spinn_front_end_common/interface/interface_functions/graph_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/placements_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/interface/provenance/pacman_provenance_extractor.py
  spinn_front_end_common/interface/provenance/provides_provenance_data_from_machine_impl.py
  spinn_front_end_common/utilities/utility_objs/power_used.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: enhancement

#780 removing very old numpy instructions with broken links
  README.md
Labels: bug

#785 _database_socket_addresses is a set
  spinn_front_end_common/interface/interface_functions/create_notification_protocol.py
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
Labels: minor

#803 Fix the provenance
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: bug

#806 Trickery to make Sphinx4 work
  doc/source/conf.py
  requirements-test.txt
Labels: bug

#811 renamed _state (not Pynn state) to status
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/simulator_status.py
Labels: minor

#812 Move the reports to FEC
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/utilities/report_functions/__init__.py
  spinn_front_end_common/utilities/report_functions/front_end_common_reports.xml
  spinn_front_end_common/utilities/report_functions/network_specification.py
  spinn_front_end_common/utilities/report_functions/reports.py
  spinn_front_end_common/utilities/report_functions/router_collision_potential_report.py
  spinn_front_end_common/utilities/report_functions/router_summary.py
  spinn_front_end_common/utilities/report_functions/routing_table_from_machine_report.py
  spinn_front_end_common/utilities/report_functions/write_json_machine.py
  spinn_front_end_common/utilities/report_functions/write_json_machine_graph.py
  spinn_front_end_common/utilities/report_functions/write_json_partition_n_keys_map.py
  spinn_front_end_common/utilities/report_functions/write_json_placements.py
  spinn_front_end_common/utilities/report_functions/write_json_routing_tables.py
Labels: enhancement

#813 nuked "unrecognized arguments: -q"
  doc/source/conf.py
Labels: bug

#814 Reset fix can of worms
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/pre_allocate_for_bit_field_router_compressor.py
Labels: bug

#810 Simplify Simulator stack
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/simulator_status.py
  spinn_front_end_common/utilities/__init__.py
  spinn_front_end_common/utilities/exceptions.py
  spinn_front_end_common/utilities/failed_state.py
  spinn_front_end_common/utilities/globals_variables.py
  spinn_front_end_common/utilities/simulator_interface.py
  unittests/test_spinnaker_main_interface.py
  unittests/utilities/__init__.py
  unittests/utilities/test_failed_state.py
Labels: enhancement
