Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2021-03, with the labels that each got.

#765 Proveance reader
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/provenance_sql_writer.py
  spinn_front_end_common/interface/provenance/.gitignore
  spinn_front_end_common/interface/provenance/__init__.py
  spinn_front_end_common/interface/provenance/provenance.sqlite3
  spinn_front_end_common/interface/provenance/provenance_reader.py
  spinn_front_end_common/utilities/constants.py
Labels: enhancement

#766 Config2
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#764 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor

#767 Remove a bad link
  doc/source/index.rst
Labels: bug, minor

#747 try again with lots of logs
  spinn_front_end_common/interface/interface_functions/system_multicast_routing_generator.py
Labels: enhancement

#768 Simplify recording
  c_common/front_end_common_lib/include/recording.h
  c_common/front_end_common_lib/src/recording.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/reverse_iptag_multicast_source/src/reverse_iptag_multicast_source.c
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/buffer_management/recording_utilities.py
  spinn_front_end_common/interface/buffer_management/storage_objects/__init__.py
  spinn_front_end_common/interface/buffer_management/storage_objects/abstract_database.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/buffer_management/storage_objects/channel_buffer_state.py
  spinn_front_end_common/interface/buffer_management/storage_objects/end_buffering_state.py
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  unittests/interface/buffer_management/test_buffered_receiver_with_db.py
Labels: enhancement

#769 Use right token for coveralls
  .github/workflows/python_actions.yml
Labels: BLOCKER!, bug, minor

#770 dont fail in error support
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#772 no need to pass self variables to private methods
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
Labels: minor

#773 remove an increment of a value never used again
  spinn_front_end_common/interface/interface_functions/system_multicast_routing_generator.py
Labels: minor

#776 Split out the shared DB setup code
  doc/unfiltered-files.txt
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/provenance/provenance_reader.py
  spinn_front_end_common/interface/provenance/router_prov_mapper.py
  spinn_front_end_common/interface/provenance/sqllite_database.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/database/database_connection.py
  spinn_front_end_common/utilities/database/database_reader.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/sqlite_db.py
Labels: enhancement

#778 Really want to get strings back in this case
  spinn_front_end_common/utilities/database/database_reader.py
Labels: blocker, bug
