Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2022-05, with the labels that each got.

#923 Whole
  fec_integration_tests/utilities/scp/test_iobuf_clear_process.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/utilities/system_control_logic.py
Labels: enhancement

#941 need the Values from the dict
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
Labels: bug

#942 Use the correct runtime value in energy reporting
  spinn_front_end_common/utilities/report_functions/energy_report.py
Labels: bug

#917 Pylint fix
  .pylintrc
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
  fec_integration_tests/interface/interface_functions/test_front_end_common_create_pre_allocated_res_for_lpg.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffered_receiving_data.py
  spinn_front_end_common/interface/buffer_management/storage_objects/sqllite_database.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/application_runner.py
  spinn_front_end_common/interface/interface_functions/chip_provenance_updater.py
  spinn_front_end_common/interface/interface_functions/database_interface.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/energy_provenance_reporter.py
  spinn_front_end_common/interface/interface_functions/graph_binary_gatherer.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_extra_monitor_functionality.py
  spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/insert_live_packet_gatherers_to_graphs.py
  spinn_front_end_common/interface/interface_functions/pre_allocate_resources_for_live_packet_gatherers.py
  spinn_front_end_common/interface/interface_functions/profile_data_gatherer.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/routing_setup.py
  spinn_front_end_common/interface/interface_functions/system_multicast_routing_generator.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/provenance/provenance_reader.py
  spinn_front_end_common/interface/provenance/provenance_writer.py
  spinn_front_end_common/utilities/fec_timer.py
  spinn_front_end_common/utilities/globals_variables.py
  spinn_front_end_common/utilities/helpful_functions.py
  spinn_front_end_common/utilities/iobuf_extractor.py
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
  spinn_front_end_common/utilities/report_functions/bit_field_compressor_report.py
  spinn_front_end_common/utilities/report_functions/board_chip_report.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
  spinn_front_end_common/utilities/report_functions/fixed_route_from_machine_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_report.py
  spinn_front_end_common/utilities/report_functions/network_specification.py
  spinn_front_end_common/utilities/report_functions/real_tags_report.py
  spinn_front_end_common/utilities/report_functions/reports.py
  spinn_front_end_common/utilities/report_functions/router_collision_potential_report.py
  spinn_front_end_common/utilities/report_functions/routing_compression_report.py
  spinn_front_end_common/utilities/report_functions/write_json_machine.py
  spinn_front_end_common/utilities/report_functions/write_json_machine_graph.py
  spinn_front_end_common/utilities/report_functions/write_json_partition_n_keys_map.py
  spinn_front_end_common/utilities/report_functions/write_json_placements.py
  spinn_front_end_common/utilities/report_functions/write_json_routing_tables.py
  spinn_front_end_common/utilities/sqlite_db.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
Labels: minor
