Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2022-09, with the labels that each got.

#975 Extdev fpgas
  spinn_front_end_common/abstract_models/__init__.py
  spinn_front_end_common/abstract_models/abstract_provides_outgoing_partition_constraints.py
  spinn_front_end_common/data/fec_data_view.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/__init__.py
  spinn_front_end_common/interface/interface_functions/command_sender_adder.py
  spinn_front_end_common/interface/interface_functions/local_tdma_builder.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/utilities/report_functions/reports.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/data/test_simulator_data.py
Labels: enhancement

#973 View holds requires
  spinn_front_end_common/abstract_models/__init__.py
  spinn_front_end_common/abstract_models/abstract_changable_after_run.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/command_sender_adder.py
Labels: enhancement

#970 Removes code to do with Virtual Chips.
  fec_integration_tests/file_convertor_tests/spinn2.json
  fec_integration_tests/file_convertor_tests/spinn4.json
  fec_integration_tests/file_convertor_tests/spinn4_fiddle.json
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/interface_functions/application_runner.py
  spinn_front_end_common/interface/interface_functions/insert_chip_power_monitors_to_graphs.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/routing_setup.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/utilities/database/database_writer.py
  spinn_front_end_common/utilities/report_functions/fixed_route_from_machine_report.py
  spinn_front_end_common/utilities/report_functions/reports.py
Labels: enhancement

#839 Tidy up debug code
  c_common/front_end_common_lib/src/data_specification.c
  c_common/models/chip_power_monitor/src/chip_power_monitor.c
  c_common/models/compressors/src/bit_field_common/bit_field_table_generator.h
  c_common/models/compressors/src/bit_field_compressor.c
  c_common/models/compressors/src/ordered_covering_includes/ordered_covering.h
  c_common/models/compressors/src/simple/rt_single.h
  c_common/models/compressors/src/simple/simple_compressor.c
  c_common/models/compressors/src/sorter/bit_field_reader.h
  c_common/models/compressors/src/sorter/bit_field_sorter_and_searcher.c
  c_common/models/live_packet_gather/src/live_packet_gather.c
  c_common/models/system_models/src/data_speed_up_packet_gatherer.c
  c_common/models/system_models/src/extra_monitor_support.c
Labels: enhancement, minor

#932 Send log messages to the database
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/provenance/__init__.py
  spinn_front_end_common/interface/provenance/db.sql
  spinn_front_end_common/interface/provenance/log_store_db.py
  spinn_front_end_common/interface/provenance/provenance_reader.py
  spinn_front_end_common/interface/provenance/provenance_writer.py
  spinn_front_end_common/interface/spinnaker.cfg
  unittests/interface/provenance/test_provenance_database.py
Labels: enhancement, in progress

#972 removed n_atoms from LegacyPartitionerAPI
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: bug

#976 Fixed location
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/interface/interface_functions/command_sender_adder.py
  spinn_front_end_common/interface/interface_functions/insert_chip_power_monitors_to_graphs.py
  spinn_front_end_common/utilities/report_functions/network_specification.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  spinn_front_end_common/utility_models/command_sender.py
  spinn_front_end_common/utility_models/command_sender_machine_vertex.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/interface/interface_functions/test_front_end_common_graph_binary_gatherer.py
Labels: enhancement

#977 Fix power monitor buffer extraction
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/interface_functions/__init__.py
  spinn_front_end_common/interface/interface_functions/buffer_extractor.py
  spinn_front_end_common/interface/interface_functions/compute_energy_used.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/locate_executable_start_type.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
Labels: bug, enhancement

#982 Single key_and_mask
  fec_integration_tests/interface/interface_functions/test_database_interface.py
  spinn_front_end_common/utilities/report_functions/reports.py
  spinn_front_end_common/utility_models/live_packet_gather_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: enhancement
