Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2022-02, with the labels that each got.

#916 write version to database ASAP
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: minor

#915 Scamp connection cleanup.
  spinn_front_end_common/interface/interface_functions/machine_generator.py
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/interface/provenance/db.sql
  spinn_front_end_common/interface/provenance/provenance_writer.py
  spinn_front_end_common/interface/spinnaker.cfg
  unittests/interface/provenance/test_provenance_database.py
Labels: enhancement

#914 range compress
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/spinnaker.cfg
Labels: enhancement

#918 Add tags where malloc is used
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py
  spinn_front_end_common/interface/interface_functions/machine_bit_field_router_compressor.py
  spinn_front_end_common/interface/interface_functions/sdram_outgoing_partition_allocator.py
  spinn_front_end_common/utilities/constants.py
Labels: bug, enhancement

#911 Where is chip
  spinn_front_end_common/utilities/globals_variables.py
Labels: minor

#920 access missing/ dead processors
  spinn_front_end_common/interface/interface_functions/compute_energy_used.py
  spinn_front_end_common/interface/interface_functions/host_bit_field_router_compressor.py
Labels: bug

#902 dont error if db never set
  spinn_front_end_common/utilities/sqlite_db.py
Labels: bug

#921 No Monitors list use dict.values()
  fec_integration_tests/test_buffer_manager_listener_creation.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/interface_functions/buffer_manager_creator.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/interface/interface_functions/insert_extra_monitor_vertices_to_graphs.py
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/utility_models/__init__.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/extra_monitor_support_machine_vertex.py
  spinn_front_end_common/utility_models/streaming_context_manager.py
Labels: enhancement

#922 Use the Data Spec database more
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/ds/__init__.py
  spinn_front_end_common/interface/ds/data_specification_targets.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/ds/ds_write_info.py
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_chip_report.py
  spinn_front_end_common/utilities/report_functions/memory_map_on_host_report.py
  spinn_front_end_common/utilities/utility_objs/__init__.py
  spinn_front_end_common/utilities/utility_objs/data_written.py
  unittests/interface/ds/test_ds_data_specification_targets.py
  unittests/interface/ds/test_ds_write_info.py
  unittests/interface/interface_functions/test_host_execute_data_specification.py
Labels: enhancement

#913 router_compressed_summary_report needs compressed router tables
  spinn_front_end_common/interface/abstract_spinnaker_base.py
Labels: bug

#924 no job to destroy if init fails
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
Labels: bug, minor
