Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2023-06, with the labels that each got.

#1073 No more len len
  spinn_front_end_common/utilities/emergency_recovery.py
Labels: bug, minor

#1071 Use UDP for live event listening to allow poking to continue to work
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
Labels: bug

#1075 Move DataType to FEC. Archive DataSpecification
  .github/workflows/python_actions.yml
  .ratexcludes
  README.md
  doc/doc_requirements.txt
  pypi_to_import
  setup.cfg
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/ds/__init__.py
  spinn_front_end_common/interface/ds/data_specification_base.py
  spinn_front_end_common/interface/ds/data_type.py
  spinn_front_end_common/utility_models/chip_power_monitor_machine_vertex.py
  unittests/test_version.py
Labels: enhancement
