Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2023-01, with the labels that each got.

#1014 skip if machines down
  fec_integration_tests/file_convertor_tests/test_write_json_machine.py
Labels: blocker

#1011 Stop the offset being 1000 microseconds or greater
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
Labels: bug

#1015 Neo database
  spinn_front_end_common/data/fec_data_view.py
  spinn_front_end_common/data/fec_data_writer.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/buffer_management/storage_objects/__init__.py
  spinn_front_end_common/interface/buffer_management/storage_objects/buffer_database.py
  spinn_front_end_common/interface/buffer_management/storage_objects/db.sql
  spinn_front_end_common/interface/interface_functions/compute_energy_used.py
  spinn_front_end_common/interface/interface_functions/energy_provenance_reporter.py
  spinn_front_end_common/interface/interface_functions/placements_provenance_gatherer.py
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/interface/java_caller.py
  spinn_front_end_common/interface/provenance/__init__.py
  spinn_front_end_common/interface/provenance/fec_timer.py
  spinn_front_end_common/interface/provenance/global.sql
  spinn_front_end_common/interface/provenance/global_provenance.py
  spinn_front_end_common/interface/provenance/log_store_db.py
  spinn_front_end_common/interface/provenance/provenance_reader.py
  spinn_front_end_common/interface/provenance/provenance_writer.py
  spinn_front_end_common/utilities/base_database.py
  spinn_front_end_common/utilities/db.sql
  spinn_front_end_common/utilities/report_functions/bit_field_compressor_report.py
  spinn_front_end_common/utilities/report_functions/energy_report.py
  spinn_front_end_common/utilities/sqlite_db.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/data/test_simulator_data.py
  unittests/interface/buffer_management/test_buffered_database.py
  unittests/interface/provenance/test_provenance_database.py
  unittests/utilities/test_fec_timer.py
Labels: enhancement
