Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2023-02, with the labels that each got.

#1017 fix raise Exception
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/buffer_management/buffer_manager.py
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/interface_functions/dsg_region_reloader.py
  spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/interface/interface_functions/virtual_machine_generator.py
  spinn_front_end_common/interface/provenance/router_prov_mapper.py
  spinn_front_end_common/utilities/connections/live_event_connection.py
  spinn_front_end_common/utilities/exceptions.py
  spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py
  unittests/data/manual_check.py
  unittests/data/test_simulator_data.py
  unittests/test_spinnaker_main_interface.py
Labels: blocker

#1003 Ds sqlite per reset which requires data generation
  spinn_front_end_common/interface/ds/ds_sqllite_database.py
  spinn_front_end_common/interface/interface_functions/graph_data_specification_writer.py
  spinn_front_end_common/interface/java_caller.py
Labels: enhancement

#1022 Spalloc server jdbc
  spinn_front_end_common/abstract_models/abstract_machine_allocation_controller.py
  spinn_front_end_common/interface/abstract_spinnaker_base.py
  spinn_front_end_common/interface/config_handler.py
  spinn_front_end_common/interface/interface_functions/spalloc_allocator.py
  spinn_front_end_common/interface/spinnaker.cfg
  spinn_front_end_common/utilities/notification_protocol/notification_protocol.py
Labels: bug

#1026 Additional router provenance
  c_common/models/system_models/src/extra_monitor_support.c
  spinn_front_end_common/interface/interface_functions/router_provenance_gatherer.py
  spinn_front_end_common/utilities/report_functions/reports.py
  spinn_front_end_common/utilities/utility_objs/reinjection_status.py
Labels: enhancement
