Repository SpiNNakerManchester/SpiNNFrontEndCommon, pull requests merged in 2023-04, with the labels that each got.

#1046 require SpiNNMan too
  setup.cfg
Labels: bug, blocker

#1049 Improve github integration
  .github/dependabot.yml
  .github/workflows/c_actions.yml
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
Labels: bug, minor

#1053 Clean up of splitter code
  fec_integration_tests/interface/interface_functions/test_database_interface.py
  spinn_front_end_common/abstract_models/impl/tdma_aware_application_vertex.py
  spinn_front_end_common/utility_models/lpg_splitter.py
  spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py
Labels: minor
